In [2]:
import numpy as np
mat_a = np.matrix([0,3,5,5,5,2]).reshape(2,3)
mat_a

matrix([[0, 3, 5],
        [5, 5, 2]])

In [10]:
mat_a = np.array([0,3,5,5,5,2]).reshape(2,3)
mat_a

array([[0, 3, 5],
       [5, 5, 2]])

In [6]:
mat_b = np.matrix([3,4,5,-2,-3,2]).reshape(3,2)
mat_b

matrix([[ 3,  4],
        [ 5, -2],
        [-3,  2]])

In [7]:
mat_a * mat_b

matrix([[ 0,  4],
        [34, 14]])

In [9]:
product = np.matmul(mat_a, mat_b)
product

matrix([[ 0,  4],
        [34, 14]])

In [11]:
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [12]:
y = np.arange(4,8).reshape(2,2)
y

array([[4, 5],
       [6, 7]])

In [17]:
z = np.hstack((x, y))
z

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [16]:
z1 = np.vstack((x, y))
z1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [18]:
z1.shape

(4, 2)

In [20]:
w = np.concatenate((x,y), axis=0)
w

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [21]:
w = np.concatenate((x,y), axis=1)
w

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [24]:
print(z == w)

[[ True  True  True  True]
 [ True  True  True  True]]


In [26]:
depth_stack = np.dstack((x,y))
depth_stack

array([[[0, 4],
        [1, 5]],

       [[2, 6],
        [3, 7]]])

In [27]:
depth_stack.shape

(2, 2, 2)

In [30]:
np.column_stack((x,y)) == np.hstack((x,y))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [31]:
np.row_stack((x,y))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [32]:
np.row_stack((x,y)) == np.vstack((x,y))

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])