In [8]:
import numpy as np
x = np.arange(18).reshape(3, 2, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [2]:
x[1,1,1]

10

In [3]:
x[1, 0:2, 0:3]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [4]:
x[1, :, :]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
print(x[: 0, 0])

[]


In [11]:

print(x[x > 5])


[ 6  7  8  9 10 11 12 13 14 15 16 17]


In [12]:
x.max()

17

In [13]:
x.min()

0

In [14]:
comp_oper = x > 5
print(comp_oper)

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]
