In [2]:
import numpy as np
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
ravelled_array = x.ravel()
ravelled_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:

ravelled_array[2] = 333
print(ravelled_array)
print(x)

[  0   1 333   3   4   5   6   7   8]
[[  0   1 333]
 [  3   4   5]
 [  6   7   8]]


In [9]:
flattened_array = x.flatten()
flattened_array[2] = 3333
print(flattened_array)
print(x)

[   0    1 3333    3    4    5    6    7    8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
y = np.arange(9)
y.shape = [3, 3]
print(y)
print(y.T) # Transpose

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [17]:
np.resize(y, (6,6))

array([[0, 1, 2, 3, 4, 5],
       [6, 7, 8, 0, 1, 2],
       [3, 4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4, 5],
       [6, 7, 8, 0, 1, 2],
       [3, 4, 5, 6, 7, 8]])

In [22]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
np.ones((4,2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.random.rand(4,4)

array([[0.27478547, 0.51393901, 0.01559089, 0.61408759],
       [0.07048343, 0.82619436, 0.36906247, 0.03413897],
       [0.20669339, 0.34160417, 0.60391587, 0.73487392],
       [0.8126039 , 0.46921872, 0.65896344, 0.71523074]])