In [1]:
list_two = list(range(1,4))
list_three = list(range(1,4))
list_sum = []

for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index] + list_three[index])
print(list_sum)



[2, 12, 36]


In [3]:
import numpy as np

array_two = np.arange(1,4) ** 2
array_three = np.arange(1,4) ** 3
print(array_two + array_three)

[ 2 12 36]


In [4]:
np.power(np.array([1,2,3]), 4)

array([ 1, 16, 81])

In [6]:
sample_array = np.power([1,2,3], 4)

In [7]:
np.negative(sample_array)

array([ -1, -16, -81])

In [8]:
  np.exp(sample_array)

array([2.71828183e+00, 8.88611052e+06, 1.50609731e+35])

In [9]:
np.log(sample_array)

array([0.        , 2.77258872, 4.39444915])

In [10]:
np.sin(sample_array)

array([ 0.84147098, -0.28790332, -0.62988799])